modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv3"
[[mods]]
modId = "mythcraft"
version = "${file.jarVersion}"
displayName = "MythCraft"
displayURL = "https://github.com/DavidQF555/MythCraft"
authors = "DavidQF555"
description = 'This mod adds in features from mythology. '